# Generated by Django 2.0.3 on 2018-08-08 11:55

from django.db import migrations, models
from django.utils import timezone


def populate_dates(apps, schema_editor):
    MobilityObservation = apps.get_model('o2', 'MobilityObservation')
    for o in MobilityObservation.objects.all():
        o.created_at = timezone.now()
        o.updated_at = timezone.now()
        o.save()

    SocioDemoObservation = apps.get_model('o2', 'SocioDemoObservation')
    for o in SocioDemoObservation.objects.all():
        o.created_at = timezone.now()
        o.updated_at = timezone.now()
        o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0004_auto_20180214_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilityobservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilityobservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sociodemoobservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sociodemoobservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunPython(populate_dates),
        migrations.AlterField(
            model_name='mobilityobservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, blank=True),
        ),
        migrations.AlterField(
            model_name='sociodemoobservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, blank=True),
        ),
        migrations.AlterField(
            model_name='mobilityobservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, blank=True),
        ),
        migrations.AlterField(
            model_name='sociodemoobservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, blank=True),
        )
    ]
