# Generated by Django 2.0.3 on 2018-04-23 05:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeteoStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_by_provider', models.CharField(editable=False, help_text='ID of the station used by provider.', max_length=50)),
                ('name', models.CharField(help_text='Human-readable name of the station.', max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(help_text='Spatial information about station.', srid=3857)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
