# Generated by Django 2.0.2 on 2018-02-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='category',
            field=models.CharField(help_text='Type of an event.', max_length=255, unique=True),
        ),
    ]
