# Generated by Django 2.0.2 on 2018-03-01 22:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminunit',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(help_text='Spatial information about feature.', srid=3857),
        ),
    ]
