# Generated by Django 2.0.3 on 2018-03-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name_plural': 'Event categories'},
        ),
    ]
