# Generated by Django 2.0.3 on 2018-03-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsd', '0002_auto_20180328_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(help_text='Type of an event.', max_length=255),
        ),
    ]
