# Generated by Django 2.0.3 on 2018-03-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsd', '0003_auto_20180328_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.TextField(help_text='Type of an event.'),
        ),
    ]
