# Generated by Django 2.0.2 on 2018-03-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsd', '0003_auto_20180303_1833'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventobservation',
            unique_together=set(),
        ),
    ]
