# Generated by Django 2.0.3 on 2018-03-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsd', '0004_auto_20180328_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='group',
            field=models.TextField(help_text='Event group.', null=True),
        ),
    ]
