# Generated by Django 2.0.2 on 2018-03-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_o2_mobility_properties_processes'),
        ('rsd', '0004_auto_20180307_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventobservation',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='eventobservation',
            unique_together={('phenomenon_time_range', 'observed_property', 'feature_of_interest', 'procedure', 'id_by_provider', 'category')},
        ),
    ]
