# Generated by Django 2.0.3 on 2018-04-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsd', '0005_eventcategory_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminunit',
            name='id_by_provider',
            field=models.CharField(help_text='ID of the station used by provider.', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventobservation',
            name='category',
            field=models.ForeignKey(help_text='Type of an event.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rsd_category', to='rsd.EventCategory'),
        ),
        migrations.AlterField(
            model_name='eventobservation',
            name='result',
            field=models.ForeignKey(help_text='Admin units of the event', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rsd_result', to='rsd.EventExtent'),
        ),
    ]
