# Generated by Django 2.0.3 on 2018-08-08 11:55

from django.db import migrations, models
from django.utils import timezone


def populate_dates(apps, schema_editor):
    Observation = apps.get_model('rsd', 'EventObservation')
    for o in Observation.objects.all():
        o.updated_at = timezone.now()
        o.created_at = timezone.now()
        o.save()

    Observation = apps.get_model('rsd', 'NumberOfEventsObservation')
    for o in Observation.objects.all():
        o.updated_at = timezone.now()
        o.created_at = timezone.now()
        o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rsd', '0005_number_of_events_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventobservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eventobservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='numberofeventsobservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='numberofeventsobservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunPython(populate_dates),
        migrations.AlterField(
            model_name='eventobservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, blank=True),
        ),
        migrations.AlterField(
            model_name='numberofeventsobservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, blank=True),
        ),
        migrations.AlterField(
            model_name='eventobservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, blank=True),
        ),
        migrations.AlterField(
            model_name='numberofeventsobservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, blank=True),
        ),
    ]
