# Generated by Django 2.0.3 on 2018-09-10 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import relativedeltafield


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_time_range_custom_functions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0, tzinfo=utc))),
                ('frequency', relativedeltafield.RelativeDeltaField()),
                ('range_from', relativedeltafield.RelativeDeltaField()),
                ('range_to', relativedeltafield.RelativeDeltaField()),
            ],
        ),
    ]
